// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.ai_card_fingerprints */
export type AiCardFingerprintsId = string & { __brand: 'public.ai_card_fingerprints' };

/** Represents the table public.ai_card_fingerprints */
export default interface AiCardFingerprints {
  id: AiCardFingerprintsId;

  owner: UsersId;

  fingerprint: string;

  created_at: Date;
}

/** Represents the initializer for the table public.ai_card_fingerprints */
export interface AiCardFingerprintsInitializer {
  /** Default value: nextval('ai_card_fingerprints_id_seq'::regclass) */
  id?: AiCardFingerprintsId;

  owner: UsersId;

  fingerprint: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.ai_card_fingerprints */
export interface AiCardFingerprintsMutator {
  id?: AiCardFingerprintsId;

  owner?: UsersId;

  fingerprint?: string;

  created_at?: Date;
}
