// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.ai_credit_grants */
export type AiCreditGrantsId = number & { __brand: 'public.ai_credit_grants' };

/** Represents the table public.ai_credit_grants */
export default interface AiCreditGrants {
  id: AiCreditGrantsId;

  user_id: UsersId;

  source: string;

  amount_credits: number;

  expires_at: Date;

  stripe_session_id: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.ai_credit_grants */
export interface AiCreditGrantsInitializer {
  /** Default value: nextval('ai_credit_grants_id_seq'::regclass) */
  id?: AiCreditGrantsId;

  user_id: UsersId;

  source: string;

  amount_credits: number;

  expires_at: Date;

  stripe_session_id?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.ai_credit_grants */
export interface AiCreditGrantsMutator {
  id?: AiCreditGrantsId;

  user_id?: UsersId;

  source?: string;

  amount_credits?: number;

  expires_at?: Date;

  stripe_session_id?: string | null;

  created_at?: Date;
}
