// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.card_guids */
export type CardGuidsId = number & { __brand: 'public.card_guids' };

/** Represents the table public.card_guids */
export default interface CardGuids {
  id: CardGuidsId;

  owner: UsersId;

  block_id: string;

  source_page_id: string | null;

  guid: string;

  created_at: Date;
}

/** Represents the initializer for the table public.card_guids */
export interface CardGuidsInitializer {
  /** Default value: nextval('card_guids_id_seq'::regclass) */
  id?: CardGuidsId;

  owner: UsersId;

  block_id: string;

  source_page_id?: string | null;

  guid: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.card_guids */
export interface CardGuidsMutator {
  id?: CardGuidsId;

  owner?: UsersId;

  block_id?: string;

  source_page_id?: string | null;

  guid?: string;

  created_at?: Date;
}
