// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ChatMessagesId } from './ChatMessages';
import type { UsersId } from './Users';

/** Identifier type for public.chat_attachments */
export type ChatAttachmentsId = number & { __brand: 'public.chat_attachments' };

/** Represents the table public.chat_attachments */
export default interface ChatAttachments {
  id: ChatAttachmentsId;

  message_id: ChatMessagesId;

  user_id: UsersId;

  s3_key: string;

  filename: string;

  content_type: string;

  byte_size: number;

  created_at: Date;
}

/** Represents the initializer for the table public.chat_attachments */
export interface ChatAttachmentsInitializer {
  /** Default value: nextval('chat_attachments_id_seq'::regclass) */
  id?: ChatAttachmentsId;

  message_id: ChatMessagesId;

  user_id: UsersId;

  s3_key: string;

  filename: string;

  content_type: string;

  byte_size: number;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.chat_attachments */
export interface ChatAttachmentsMutator {
  id?: ChatAttachmentsId;

  message_id?: ChatMessagesId;

  user_id?: UsersId;

  s3_key?: string;

  filename?: string;

  content_type?: string;

  byte_size?: number;

  created_at?: Date;
}
