// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.conversion_result_cache */
export type ConversionResultCacheId = number & { __brand: 'public.conversion_result_cache' };

/** Represents the table public.conversion_result_cache */
export default interface ConversionResultCache {
  id: ConversionResultCacheId;

  cache_key: string;

  model: string;

  prompt_version: string;

  deck_info: unknown;

  card_count: number;

  hits: number;

  created_at: Date;

  last_accessed_at: Date;
}

/** Represents the initializer for the table public.conversion_result_cache */
export interface ConversionResultCacheInitializer {
  /** Default value: nextval('conversion_result_cache_id_seq'::regclass) */
  id?: ConversionResultCacheId;

  cache_key: string;

  model: string;

  prompt_version: string;

  deck_info: unknown;

  /** Default value: 0 */
  card_count?: number;

  /** Default value: 0 */
  hits?: number;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  last_accessed_at?: Date;
}

/** Represents the mutator for the table public.conversion_result_cache */
export interface ConversionResultCacheMutator {
  id?: ConversionResultCacheId;

  cache_key?: string;

  model?: string;

  prompt_version?: string;

  deck_info?: unknown;

  card_count?: number;

  hits?: number;

  created_at?: Date;

  last_accessed_at?: Date;
}
