// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.conversion_rule_scores */
export type ConversionRuleScoresId = number & { __brand: 'public.conversion_rule_scores' };

/** Represents the table public.conversion_rule_scores */
export default interface ConversionRuleScores {
  id: ConversionRuleScoresId;

  created_at: Date;

  owner: UsersId | null;

  source: string;

  engine: string;

  input_format: string;

  rule: string;

  was_fallback: boolean;

  outcome: string;

  scorer_version: number;

  card_count: number;

  card_chars: number;

  doc_chars: number;

  median_front_len: number;

  median_back_len: number;

  blank_back_rate: number;

  duplicate_front_rate: number;

  balance: number;
}

/** Represents the initializer for the table public.conversion_rule_scores */
export interface ConversionRuleScoresInitializer {
  /** Default value: nextval('conversion_rule_scores_id_seq'::regclass) */
  id?: ConversionRuleScoresId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  owner?: UsersId | null;

  source: string;

  engine: string;

  input_format: string;

  rule: string;

  /** Default value: false */
  was_fallback?: boolean;

  outcome: string;

  /** Default value: 1 */
  scorer_version?: number;

  card_count: number;

  card_chars: number;

  doc_chars: number;

  median_front_len: number;

  median_back_len: number;

  blank_back_rate: number;

  duplicate_front_rate: number;

  balance: number;
}

/** Represents the mutator for the table public.conversion_rule_scores */
export interface ConversionRuleScoresMutator {
  id?: ConversionRuleScoresId;

  created_at?: Date;

  owner?: UsersId | null;

  source?: string;

  engine?: string;

  input_format?: string;

  rule?: string;

  was_fallback?: boolean;

  outcome?: string;

  scorer_version?: number;

  card_count?: number;

  card_chars?: number;

  doc_chars?: number;

  median_front_len?: number;

  median_back_len?: number;

  blank_back_rate?: number;

  duplicate_front_rate?: number;

  balance?: number;
}
