// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.deck_distribution_intent */
export type DeckDistributionIntentId = number & { __brand: 'public.deck_distribution_intent' };

/** Represents the table public.deck_distribution_intent */
export default interface DeckDistributionIntent {
  id: DeckDistributionIntentId;

  answer: string;

  notify_email: string | null;

  user_id: UsersId;

  upload_key: string;

  created_at: Date;
}

/** Represents the initializer for the table public.deck_distribution_intent */
export interface DeckDistributionIntentInitializer {
  /** Default value: nextval('deck_distribution_intent_id_seq'::regclass) */
  id?: DeckDistributionIntentId;

  answer: string;

  notify_email?: string | null;

  user_id: UsersId;

  upload_key: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.deck_distribution_intent */
export interface DeckDistributionIntentMutator {
  id?: DeckDistributionIntentId;

  answer?: string;

  notify_email?: string | null;

  user_id?: UsersId;

  upload_key?: string;

  created_at?: Date;
}
