// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.email_change_tokens */
export type EmailChangeTokensId = number & { __brand: 'public.email_change_tokens' };

/** Represents the table public.email_change_tokens */
export default interface EmailChangeTokens {
  id: EmailChangeTokensId;

  user_id: UsersId;

  new_email: string;

  token_hash: string;

  expires_at: Date;

  consumed_at: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.email_change_tokens */
export interface EmailChangeTokensInitializer {
  /** Default value: nextval('email_change_tokens_id_seq'::regclass) */
  id?: EmailChangeTokensId;

  user_id: UsersId;

  new_email: string;

  token_hash: string;

  expires_at: Date;

  consumed_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.email_change_tokens */
export interface EmailChangeTokensMutator {
  id?: EmailChangeTokensId;

  user_id?: UsersId;

  new_email?: string;

  token_hash?: string;

  expires_at?: Date;

  consumed_at?: Date | null;

  created_at?: Date;
}
