// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.held_decks */
export type HeldDecksId = number & { __brand: 'public.held_decks' };

/** Represents the table public.held_decks */
export default interface HeldDecks {
  id: HeldDecksId;

  storage_key: string;

  anon_id: string;

  filename: string;

  card_count: number;

  cards_held_back: number;

  created_at: Date;

  expires_at: Date;

  claimed_at: Date | null;

  claimed_by: UsersId | null;
}

/** Represents the initializer for the table public.held_decks */
export interface HeldDecksInitializer {
  /** Default value: nextval('held_decks_id_seq'::regclass) */
  id?: HeldDecksId;

  storage_key: string;

  anon_id: string;

  filename: string;

  card_count: number;

  cards_held_back: number;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  expires_at: Date;

  claimed_at?: Date | null;

  claimed_by?: UsersId | null;
}

/** Represents the mutator for the table public.held_decks */
export interface HeldDecksMutator {
  id?: HeldDecksId;

  storage_key?: string;

  anon_id?: string;

  filename?: string;

  card_count?: number;

  cards_held_back?: number;

  created_at?: Date;

  expires_at?: Date;

  claimed_at?: Date | null;

  claimed_by?: UsersId | null;
}
