// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { AnonymousPassesId } from './AnonymousPasses';

/** Identifier type for public.pass_claim_tokens */
export type PassClaimTokensId = number & { __brand: 'public.pass_claim_tokens' };

/** Represents the table public.pass_claim_tokens */
export default interface PassClaimTokens {
  id: PassClaimTokensId;

  user_id: UsersId | null;

  anonymous_pass_id: AnonymousPassesId;

  token_hash: string;

  expires_at: Date;

  consumed_at: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.pass_claim_tokens */
export interface PassClaimTokensInitializer {
  /** Default value: nextval('pass_claim_tokens_id_seq'::regclass) */
  id?: PassClaimTokensId;

  user_id?: UsersId | null;

  anonymous_pass_id: AnonymousPassesId;

  token_hash: string;

  expires_at: Date;

  consumed_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.pass_claim_tokens */
export interface PassClaimTokensMutator {
  id?: PassClaimTokensId;

  user_id?: UsersId | null;

  anonymous_pass_id?: AnonymousPassesId;

  token_hash?: string;

  expires_at?: Date;

  consumed_at?: Date | null;

  created_at?: Date;
}
