// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.subscriptions_developer */
export type SubscriptionsDeveloperId = number & { __brand: 'public.subscriptions_developer' };

/** Represents the table public.subscriptions_developer */
export default interface SubscriptionsDeveloper {
  id: SubscriptionsDeveloperId;

  stripe_subscription_id: string;

  user_id: UsersId | null;

  email: string | null;

  stripe_product_id: string;

  active: boolean;

  payload: unknown;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.subscriptions_developer */
export interface SubscriptionsDeveloperInitializer {
  /** Default value: nextval('subscriptions_developer_id_seq'::regclass) */
  id?: SubscriptionsDeveloperId;

  stripe_subscription_id: string;

  user_id?: UsersId | null;

  email?: string | null;

  stripe_product_id: string;

  /** Default value: false */
  active?: boolean;

  payload: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.subscriptions_developer */
export interface SubscriptionsDeveloperMutator {
  id?: SubscriptionsDeveloperId;

  stripe_subscription_id?: string;

  user_id?: UsersId | null;

  email?: string | null;

  stripe_product_id?: string;

  active?: boolean;

  payload?: unknown;

  created_at?: Date;

  updated_at?: Date;
}
